### ISSUE TITLE
Prop Name Casing

### ISSUE THREAD

**Issue by yeefun** [mirror-media/mirror-media-nuxt#17]
[Vue 官網建議](https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended)在 `templates` 上使用 kebab-case，在聲明時使用 camelCase。原因是遵循每個語言自己的約定。

但 prop name 都用 camelCase，有以下好處：
- 腦袋不需多一層轉換。
- 可以直接複製貼上。
- 方便在不同檔案之間搜尋。
- 可以區分哪些是 HTML 本來就有的屬性，哪些是透過 Vue 才能加上去的。

## 結論
- prop name 都使用 camelCase。

## 行動
- 更改 [eslint-plugin-vue 的設定](https://eslint.vuejs.org/rules/attribute-hyphenation.html)。

**Comment by kwhsiung** [comment]
這個 issue 是否應該是要修改 [vue/attribute-hyphenation](https://eslint.vuejs.org/rules/attribute-hyphenation.html) 而不是 [vue/prop-name-casing](https://eslint.vuejs.org/rules/prop-name-casing.html) 才對，vue/prop-name-casing 指的是 component 內部定義 props 的命名規則，而不是使用者在使用上的命名規則。

**Comment by yeefun** [comment]
沒錯，我搞錯了。感謝提醒，連結已經修改。
