### ISSUE TITLE
將 dev 設為 default branch

### ISSUE THREAD

**Issue by kwhsiung** [mirror-media/mirror-media-nuxt#18]
因為 PR https://github.com/mirror-media/mirror-media-nuxt/pull/16 中的 message 已經含有 resolve issue 的關鍵字，但 merge 之後發現沒有 close issue https://github.com/mirror-media/mirror-media-nuxt/issues/15

據 [Closing Issues via Pull Requests](https://github.blog/2013-05-14-closing-issues-via-pull-requests/) 提到：
> And the referenced issue will automatically be closed when the PR is merged
into the default branch.

而以我們現在的 workflow 來說 PR 大多發在 dev branch，若想透過 PR 來自動 close issue 我們需要在 GitHub 上將 dev 設為 default branch。

**Comment by hsuehyungtan** [comment]
ok 直接改吧

**Comment by kwhsiung** [comment]
done
