### ISSUE TITLE
在 vue 中使用 auto-loadmore/infinite-scroll 的解決方案

### ISSUE THREAD

**Issue by kwhsiung** [mirror-media/mirror-media-nuxt#37]
關於 auto-loadmore/infinite-scroll 不知道 @hsuehyungtan 跟 @yeefun 有沒有一些解決方案或意見可以提供？
我目前知道的一些方案有：
1. https://github.com/ElemeFE/vue-infinite-scroll
    - 目的單純：單純透過 custom directive 告知需不需要 loadmore。
    - 沒在維護了。
2. https://github.com/PeachScript/vue-infinite-loading
    - 功能多元：除了核心的告知 loadmore 功能，還多了很多其他功能（如 loading icon）。
    - 目前還有在維護。
3. 自幹

我個人用過 1.，雖然久沒維護了，但目前也沒有遇到什麼問題。
由於我個人預想的目的是希望在使用上能夠簡單易用（使用者不用做一堆手動 import 或額外在 mounted hook 中設置 event handler），可能會比較朝先直接用 1. or 2.，有時間再深入研究如何走 3.。

**Comment by hsuehyungtan** [comment]
個人傾向 2 或 3，比較偏好 2，因為文件看起來滿完整的，又有持續維護。

1 看了 issue 覺得可能會有隱藏的 bug，基於沒有繼續維護的情況，未來如果踩到 bug，要 debug 的成本可能跟自幹差不多，所以不建議使用這個

**Comment by yeefun** [comment]
偏好 2，但如果功能沒有用很多，會偏好 3。
附上 package 的大小（[在這邊查的](https://bundlephobia.com/)）：

vue-infinite-scroll
<img width="1051" alt="螢幕快照 2020-05-08 12 14 49" src="https://user-images.githubusercontent.com/32699979/81370300-6a379100-9127-11ea-9db8-3960c10d23e5.png">

vue-infinite-loading
<img width="1051" alt="螢幕快照 2020-05-08 12 13 45" src="https://user-images.githubusercontent.com/32699979/81370320-74f22600-9127-11ea-9fc5-0b34e99ff1fd.png">

**Comment by kwhsiung** [comment]
Ok, 那我目前會先在 listing 頁試著導入 https://github.com/PeachScript/vue-infinite-loading，然後不會 install as a global vue plugin，只會先試著在 listing 頁 install locally，避免 app.js bundle 太大包。
