### ISSUE TITLE
API request 共用工具

### ISSUE THREAD

**Issue by hsuehyungtan** [mirror-media/mirror-media-nuxt#41]
想問你們使用上偏好哪一種方式 @kwhsiung @yeefun 

問題 A : plugin Injected function 風格
1. `$request('/getlist', { page: 1, maxResults: 10 })`
完全彈性，但需要自己填上 endpoint

2. `$requestGetList({ page: 1, maxResults: 10 })`
每個 endpoint 都有對應的 function

問題 B: params `where` 處理
1. `$xxx({ page: 1, where: { categories: { $in: [ 'xxxx', 'xxxx ] }}})`
完全依照原本後端階層，不做任何簡化

2. `$xxx({ page: 1, where: { categories: [ 'xxxx', 'xxxx ]}})`
將 where 下特定的 key 的階層做簡化

3. `$xxx({ page: 1, categories: [ 'xxxx', 'xxxx ]})`
攤平 where 這一層並做簡化，轉換後除了 `page`, `maxResults` 等原本第一層的之外，都會放在 `where` 下

問題 C: 空陣列處理
目前如果 request 的資料是空的話，會回 status code 200 然後是空陣列，需要轉為 throw error 嗎？

**Comment by kwhsiung** [comment]
問題 A：
偏好 2，我認為這樣比較有統一性，往後也方便對這個統一接口做一些修改。

問題 B：
偏好 3，然後我提議可以利用 [debug](https://www.npmjs.com/package/debug) 在發生非預期情況時可以 log 出原始的後端階層供查看。

問題 C：
用 error 的方式我認為差別在使用方的處理比較可以有組織性，譬如各 page component 中進入頁面時 server-side 拉資料遇到 404, 500 的處理邏輯都在 `catch`，但換句話說處理 404 與 500 的邏輯散布在 `then` 及 `catch` 也可以 work（先忽略我們實際可能是用 `async/await`），其實我想確認這個情境 status code 是 404 嗎？

**Comment by hsuehyungtan** [comment]
討論結果：

問題 A：選用 2 方案
問題 B：選用 3 方案
問題 C：throw error
