### ISSUE TITLE
將 sass 改成 scss

### ISSUE THREAD

**Issue by yeefun** [mirror-media/mirror-media-nuxt#44]
要先麻煩 @kwhsiung 改 sass 資料夾裡的檔案，我們再改自己的 component 的 style（只改 component 的 style，如果用到 `@include media-breakpoint-**`，會報錯）。

**Comment by kwhsiung** [comment]
done: https://github.com/mirror-media/mirror-media-nuxt/pull/45

**Comment by yeefun** [comment]
done: #46
