### ISSUE TITLE
將一些 nuxt packages 從 modules 移動到 buildModules

### ISSUE THREAD

**Issue by kwhsiung** [mirror-media/mirror-media-nuxt#47]
https://nuxtjs.org/guide/modules/#build-only-modules
nuxt 建議一些 packages 擺放在 nuxt.config.js 中 buildModules 而非 modules，因為確實會對效能造成一些影響。
以我們[目前的擺放方式](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/nuxt.config.js#L51)，有以下兩個 packages 需要移動：
1. [`@nuxtjs/google-analytics`](https://github.com/nuxt-community/analytics-module#setup)
2. [`@nuxtjs/style-resources`](https://github.com/nuxt-community/style-resources-module#setup)

**Comment by yeefun** [comment]
@nuxtjs/google-analytics 的擺放位置會跟 GA 新設定一起改（這部分我已經快處理完了）。

**Comment by kwhsiung** [comment]
那把這個 issue assign 給你囉，再麻煩你用 PR resolve 掉。
