### ISSUE TITLE
node升版到v16

### ISSUE THREAD

**Issue by dyfu95** [mirror-media/mirror-media-nuxt#643]
(WIP)
我有一個提案，想跟大家討論：**將週刊使用的node version，從14升到16。**
原因有三：

1. 16版是m1 native，在m1 的電腦上有更好的開發體驗：
   對我而言，這是升到v16的最主要原因。
   依據官方的[v16 change log](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#toolchain-and-compiler-upgrades)，v16 有支援m1 native。雖然我個人沒有看得很懂，但爬了一下文，大概就是在m1上有更快的速度。
   而根據我自己實測（mac m1 2020 8G），在v14 中，下`yarn dev`後大約需要40秒才會compile完成，v16則只需要25秒左右；v14中`yarn build`需要約50秒才能build好，v16則只需要25-30秒。此外，在HMR（hot module replacement）模式下，v14大約仍須體感1-1.5秒才能complied 完畢，v16則幾乎不用時間。簡單來說，我認為升級到v16，能夠大幅提升開發上的體驗。
3. V8引擎升級，提升效能：
    16版使用了9.0版的V8 引擎，依據官方[change log](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#v8-90)，這能帶來更好的效能。但這部分，就開發上很難肉眼看得出來，也許需要一些分析工具檢測是否屬實。
1. 14版目前已經進入maintain mode，而且將於2023.4進入為End-of-Life：
    依據node官方的[Release plan](https://github.com/nodejs/Release)，目前LTS（Long Time Support）的版本分別有14跟16，但是14目前已經進入maintain mode，而且明年將進入EOL(End-of-Life)。這意味著明年四月後，[node官方將不再處理bug與security issue](https://nodesource.com/blog/understanding-how-node-js-release-lines-work/#:~:text=EOL%3A%20EOL%20is%20an%20acronym%20for%20End%20of%20Life.%20Node.js%20versions%20that%20are%20EOL%20are%20no%20longer%20maintained%2C%20and%20will%20not%20be%20patched%20with%20fixes%20for%20bugs%20or%20known%20security%20vulnerabilities.)。我認為，除非有套件是指定使用低版本的node，不然使用沒有團隊維護的node，是件危險且沒必要的事。

綜合上述三點，我認為升到16沒有壞處，只有好處，而且也有升級的必要性。

而我目前把node升版後所衍生的bug與相關的解法，會放在 #642  上。（待補）

**Comment by erase2004** [comment]
這應該可以關了
