### ISSUE TITLE
Refactoring 眾多 listing pages，使重複的程式碼減少

### ISSUE THREAD

**Issue by kwhsiung** [mirror-media/mirror-media-nuxt#69]
Reference: https://github.com/mirror-media/mirror-media-nuxt/pull/63

目前的 listing pages 條列如下，當中有許多程式碼屬重複部分，可考慮重構：
- 已實作：
  - [`/pages/author/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/author/_id.vue)
  - [`/pages/category/_name.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/category/_name.vue)
  - [`/pages/search/_keyword.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/search/_keyword.vue)
  - [`/pages/section/_name.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/section/_name.vue)
  - [`/pages/section/topic.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/section/topic.vue)
  - [`/pages/tag/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/tag/_id.vue) 
  - [`/pages/topic/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/topic/_id.vue) 

在 nuxt 中令多個 routes 可共用同一個 page component 而減少 page components 數量的方法參考：https://github.com/nuxt/nuxt.js/issues/2693#issuecomment-408584512

**Comment by kwhsiung** [comment]
這部分的重構我有計畫要引入 composition api 來輔助，由於 composition api 使用上需要手動 import 相關 function 並透過 [setup](https://composition-api.vuejs.org/#basic-example) 來使用，故引入之後不會直接影響既有的 components，可漸進式的使用，所以引入之後應該不會直接破壞目前的系統。

**Comment by kwhsiung** [comment]
Note: IE11

**Comment by kwhsiung** [comment]
# Default listing pages 現有功能紀錄
- 廣告
  - GPT: top and bottom
  - MicroAd: listing 項目的第 3, 5, 8 個項目為廣告

# Default listing pages 各頁功能列表
- [`/pages/author/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/author/_id.vue)
  - 廣告：✅
- [`/pages/category/_name.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/category/_name.vue)
  - 廣告：✅
- [`/pages/search/_keyword.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/search/_keyword.vue)
  - 廣告：❌
- [`/pages/section/_name.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/section/_name.vue)
  - 廣告：✅
- [`/pages/section/topic.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/section/topic.vue)
  - 廣告：✅
- [`/pages/tag/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/tag/_id.vue) 
  - 廣告：✅
- [`/pages/topic/_id.vue`](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/pages/topic/_id.vue) 
  - 廣告：❌

**Comment by kwhsiung** [comment]
# 重構方法
依我個人認為重構後的結果依收斂（需要越少檔案越收斂）程度由小到大排序

- 已知方法
  1. 將同質性的功能（利用 composition api）封裝。
  2. [維持檔案結構定義 routes，但 page component 其實直接吃另一個 page component 的定義。
](https://github.com/mirror-media/mirror-voice/blob/960e91b48d8638966b9087c3ab1340ea80dec45a/pages/category/_name.vue)
      - 優：維持 nuxt 預設定義 page routes 的方式，減少往後溝通成本。
      - 缺：檔案結構依然有很多 default listing pages，且很多 page components 內容打開來發現內容其實都是吃同一個 component。
  3. [捨棄檔案結構定義 routes，在 nuxt.config.js 中用 extendRoutes 來讓重複性高的 pages components 都導向某一個樣板。
](https://github.com/nuxt/nuxt.js/issues/2693#issuecomment-408584512)
      - 優：檔案結構不再看到一堆 default listing pages。
      - 缺：不再使用 nuxt 預設的定義 page routes 方式，且可能同時有兩種定義 page routes 的方式並存，溝通成本增加。

**Comment by yeefun** [comment]
Mixin: [fetch-list-and-loadmore.js](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/mixins/fetch-list-and-loadmore.js)
Component: [ContainerList.vue](https://github.com/mirror-media/mirror-media-nuxt/blob/dev/components/ContainerList.vue)
